# 사이킷런기반 머신러닝

## 사이킷런(scikit-learn)의 특징
- 파이썬 머신러닝 라이브러리 중 가장 많이 사용되는 라이브러리
- 사이트 : https://scikit-learn.org/stable/
- 머신러닝을 위한 매우 다양한 알고리즘과 개발을 위한 편리한 프레임워크와 API 제공
- 주로 Numpy와 Scipy 기반 위에서 구축된 라이브러리
- Scikit-learn algorithm cheat-sheet
    - https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

## 머신러닝 프로세스

<img src="./img/머신러닝프로세스.jpg" width=800 align=left>

### 경고 무시

In [ ]:
# 경고 무시
import warnings
warnings.filterwarnings(action='ignore')

### sklearn 모듈 설치 및 불러오기

In [ ]:
!pip install sklearn

Collecting sklearn
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [ ]:
import sklearn
sklearn.__version__

'1.6.1'

------
## 지도학습 - 분류

In [ ]:
import os
import urllib.request

# 1. ./data 폴더 생성 (이미 존재하면 무시)
os.makedirs("./data", exist_ok=True)

# 2. 온라인 Iris 데이터셋을 ./data/iris.csv 경로로 다운로드
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
urllib.request.urlretrieve(url, "./data/iris.csv")

('./data/iris.csv', <http.client.HTTPMessage at 0x7cf5b6a856d0>)

### 1. 데이타 준비하기

In [ ]:
import pandas as pd
df = pd.read_csv("./data/iris.csv")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df.shape

(150, 5)

### 2. 데이타 전처리

#### 필수 1) 결측치 처리

In [ ]:
# 결측치 확인
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

#### 필수2) 데이타 인코딩 : 범주형 데이타 -> 레이블 인코딩

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
origin_target = ['setosa', 'versicolor', 'virginica']

In [ ]:
df['species'] = df['species'].str.replace('setosa', '0').replace('versicolor', '1').replace('virginica', '2').astype('int32')

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

### 3. 데이타 분리하기
- 1) 종속변수와 설명변수 구분
- 2) 학습 데이터셋과 테스트 데이터셋 분리: train_test_split() 함수
    - `train_test_split(arrays, test_size, train_size, random_state, shuffle, stratify)`

#### 1) 종속변수와 설명변수 구분

In [ ]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

#### 2) 학습 데이터셋과 테스트 데이터셋 분리: train_test_split() 함수

In [ ]:
from sklearn.model_selection import train_test_split

# 학습데이터셋과 테스트데이터셋 구분 - 70:30
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3,
                                                    random_state=0)

In [ ]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(105, 4) (105,)
(45, 4) (45,)

### 4. 지도학습 - 분류

#### 1) 분류 모델

In [ ]:
# 지도학습 - 분류 : 의사결정트리
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()  # 1) 모델 선정
clf.fit(X_train, y_train)       # 2) 모델 학습
y_pred = clf.predict(X_test)    # 3) 예측
clf.score(X_test, y_test)       # 4) 평가(정확도)

0.9777777777777777

#### 2) 분류 모델 평가

In [ ]:
# 분류 모델의 평가
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9777777777777777

#### 3) 예측

In [ ]:
idx = int(clf.predict([[4.6, 352, 2.3, 3.2]]))
print(origin_target[idx])

setosa

#### 4) 과적합의 유무 확인

In [ ]:
from sklearn.metrics import accuracy_score
y_train_pred = clf.predict(X_train) # 학습 데이타 예측
y_test_pred = clf.predict(X_test)   # 테스트 데이타 예측
print('학습데이타 예측 정확도 : %.4f' % accuracy_score(y_train, y_train_pred))

학습데이타 예측 정확도 : 1.0000
테스트데이타 예측 정확도 : 0.9778

### 5. 교차 검증
- K-Fold Cross Validation(K-겹 교차검증) : cross_val_score() 함수

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

# 데이타 불러오기
df = pd.read_csv("./data/iris.csv")

# 데이타 전처리
df['species'] = df['species'].str.replace('setosa', '0').replace('versicolor', '1').replace('virginica', '2').astype('int32')

# 데이타 분리하기
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

X_train, X_test,y_train, y_test= train_test_split(X, y,
                                                  test_size=0.3,
                                                  random_state=0)

clf = DecisionTreeClassifier( )   # 1) 모델 선택
clf.fit(X_train, y_train)         # 2) 학습 - fit()
y_pred = clf.predict(X_test)      # 3) 예측 - predict()

print('예측 정확도: %.4f' % accuracy_score(y_test, y_pred))

예측 정확도: 0.9778

#### 10-Fold 교차 검증

In [ ]:
from sklearn.model_selection import cross_val_score

score = cross_val_score(clf ,X_train, y_train, cv=10 )
print(score)
print(score.mean())

[1.         1.         0.90909091 1.         1.         1.
 0.9        0.8        1.         0.9       ]
0.9509090909090909

------
## 지도학습 - 회귀

### 1. 데이타 준비하기

In [ ]:
import pandas as pd
df = pd.read_csv("./data/iris.csv")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df.shape

(150, 5)

### 2. 데이타 전처리

#### 필수 1) 결측치 처리

In [ ]:
# 결측치 확인
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

#### 필수2) 데이타 인코딩 : 범주형 데이타 -> 레이블 인코딩

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
df['species'] = df['species'].str.replace('setosa', '0').replace('versicolor', '1').replace('virginica', '2').astype('int32')

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

### 3. 데이타 분리하기
- 1) 종속변수와 설명변수 구분
- 2) 학습 데이터셋과 테스트 데이터셋 분리: train_test_split() 함수
    - `train_test_split(arrays, test_size, train_size, random_state, shuffle, stratify)`

#### 1) 종속변수와 설명변수 구분

In [ ]:
X = df.iloc[:, 1:]
y = df.iloc[:, 1]

In [ ]:
X

     sepal_width  petal_length  petal_width  species
0            3.5           1.4          0.2        0
1            3.0           1.4          0.2        0
2            3.2           1.3          0.2        0
3            3.1           1.5          0.2        0
4            3.6           1.4          0.2        0
..           ...           ...          ...      ...
145          3.0           5.2          2.3        2
146          2.5           5.0          1.9        2
147          3.0           5.2          2.0        2
148          3.4           5.4          2.3        2
149          3.0           5.1          1.8        2

[150 rows x 4 columns]

In [ ]:
y

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

#### 2) 학습 데이터셋과 테스트 데이터셋 분리: train_test_split() 함수

In [ ]:
from sklearn.model_selection import train_test_split

# 학습데이터셋과 테스트데이터셋 구분 - 70:30
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3,
                                                    random_state=0)

In [ ]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(105, 4) (105,)
(45, 4) (45,)

### 4. 지도학습 - 회귀

#### 1) 회귀 분석 모델

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()      # 1) 모델 선정
lr.fit(X_train, y_train)     # 2) 모델 학습
y_pred = lr.predict(X_test)    # 3) 예측
lr.score(X_test, y_test)     # 4) 평가(R^2)

1.0

In [ ]:
print("절편: %.5f" % lr.intercept_)
print("회귀계수:", lr.coef_)

절편: -0.00000
회귀계수: [1.00000000e+00 9.12852086e-17 3.15053208e-17 2.57313002e-17]

#### 2) 회귀 분석모델 평가

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R^2 :", r2_score(y_test, y_pred))

MSE : 8.326865110666236e-32
RMSE : 2.885630799438181e-16
R^2 : 1.0

#### 3) 예측

In [ ]:
X_test[:1]

     sepal_width  petal_length  petal_width  species
114          2.8           5.1          2.4        2

In [ ]:
result = float(lr.predict([[4.6, 7.1, 2.3, 1]]))
print("예측된 sepal_width :", round(result,1))

예측된 sepal_width : 4.6

#### 4) 과적합의 유무 확인

In [ ]:
from sklearn.metrics import mean_squared_error
y_train_pred = lr.predict(X_train) # 학습 데이타 예측
y_test_pred = lr.predict(X_test)   # 테스트 데이타 예측
print('학습데이타 MSE : %.4f' % mean_squared_error(y_train, y_train_pred))
print('테스트데이타 MSE : %.4f' % mean_squared_error(y_test, y_test_pred))

학습데이타 MSE : 0.0000
테스트데이타 MSE : 0.0000

### 5. 교차 검증
- K-Fold Cross Validation(K-겹 교차검증) : cross_val_score() 함수

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd
import numpy as np

# 데이타 불러오기
df = pd.read_csv("./data/iris.csv")

# 데이타 전처리
df['species'] = df['species'].str.replace('setosa', '0').replace('versicolor', '1').replace('virginica', '2').astype('int32')

# 데이타 분리하기
X = df.iloc[:, 1:]
y = df.iloc[:, 1]

X_train, X_test,y_train, y_test= train_test_split(X, y,
                                                  test_size=0.3,
                                                  random_state=0)

lr = LinearRegression()      # 1) 모델 선정
lr.fit(X_train, y_train)     # 2) 모델 학습
y_pred = lr.predict(X_test)  # 3) 예측

print("MSE :", mean_squared_error(y_test, y_pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R^2 :", r2_score(y_test, y_pred))

MSE : 8.326865110666236e-32
RMSE : 2.885630799438181e-16
R^2 : 1.0

#### 10-Fold 교차 검증

In [ ]:
from sklearn.model_selection import cross_val_score

score = cross_val_score(lr ,X_train, y_train, cv=10 )
print(score)
print(score.mean())

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
1.0